name: Create .env File

on:
  push:
    branches:
      - main

jobs:
  create-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create .env file from secrets
        run: |
          printf '%b' "${{ secrets.ENV }}" > .env
